/**
 * Formats a date object to a string
 * @param {Date} date - The date to format
 * @returns {string} - The formatted date string
 */
const formatDate = (date = new Date()) => {
  return date.toISOString();
};

const positions = [
  // Executive & Leadership
  'ceo', 'coo', 'cfo', 'cto', 'cio', 'cmo', 'cso', 'chro', 'cdo', 'cpo',
  'president', 'vice president', 'vp', 'executive director', 'managing director',
  'director', 'assistant director', 'general manager', 'associate director', 'head of department',
  'المدير التنفيذي','المدير التنفيذي للعمليات','المدير المالي','المدير التقني','رئيس قسم المعلومات',
  'المدير التسويقي','رئيس قسم الأمن','رئيس الموارد البشرية','رئيس قسم البيانات','رئيس قسم المنتجات',
  'الرئيس','نائب الرئيس', 'نائب الرئيس','المدير التنفيذي', 'المدير العام', 'المدير','مساعد مدير',
  'المدير العام', 'مدير مشارك', 'رئيس القسم', 'मुख्य कार्यकारी अधिकारी','मुख्य संचालन अधिकारी','मुख्य वित्तीय अधिकारी',
  'मुख्य तकनीकी अधिकारी','मुख्य सूचना अधिकारी','मुख्य विपणन अधिकारी','मुख्य सुरक्षा अधिकारी','मुख्य मानव संसाधन अधिकारी',
  'मुख्य डेटा अधिकारी','मुख्य उत्पाद अधिकारी','अध्यक्ष','उपाध्यक्ष','उपाध्यक्ष','कार्यकारी निदेशक','प्रबंध निदेशक','निदेशक',
  'सहायक निदेशक','महाप्रबंधक','सहायक निदेशक','विभाग प्रमुख','verkställande direktör','operativ chef','finanschef',
  'teknisk chef','it-chef','marknadschef','säkerhetschef','personalchef','dataansvarig','produktchef',
  'president','vice president','vp','verkställande direktör','verkställande chef','direktör',
  'biträdande direktör','generaldirektör','biträdande direktör','avdelningschef','מנכ"ל','ראש תפעול',
  'ראש כספים','ראש טכנולוגיות','ראש מערכות מידע','ראש שיווק','ראש אבטחה','ראש משאבי אנוש','ראש דיגיטל',
  'ראש מוצר','נשיא','סגן נשיא','סגן נשיא', 'מנהל כללי','מנכ"ל משותף','מנהל','סגן מנהל','מנהל כללי',
  'סגן מנהל','ראש המחלקה',


  // Technology & Engineering
  'software engineer', 'frontend developer', 'backend developer', 'full stack developer',
  'web developer', 'mobile developer', 'qa engineer', 'test engineer', 'devops engineer',
  'cloud engineer', 'site reliability engineer', 'ai engineer', 'machine learning engineer',
  'data engineer', 'data scientist', 'data analyst', 'business intelligence analyst',
  'ux designer', 'ui designer', 'product designer', 'graphic designer', 'game developer',
  'embedded systems engineer', 'firmware developer', 'ar/vr developer', 'systems administrator',
  'network engineer', 'security engineer', 'blockchain developer', 'robotics engineer',
  'database administrator', 'hardware engineer', 'it support specialist',
  'solutions architect', 'enterprise architect', 'technical writer', 'it manager',
  'technical support engineer',
  'مهندس برمجيات','مطوّر الواجهة الأمامية','مطوّر الواجهة الخلفية','مطوّر متكامل', 
  'مطوّر ويب','مطوّر تطبيقات الهاتف','مهندس ضمان الجودة','مهندس اختبارات','مهندس ديف أوبس',
  'مهندس سحابة','مهندس موثوقية الموقع', 'مهندس ذكاء اصطناعي','مهندس تعلم آلي', 
  'مهندس بيانات','عالِم بيانات','محلل بيانات','محلل استخبارات الأعمال', 'مصمم تجربة المستخدم',
  'مصمم واجهة المستخدم','مصمم منتج','مصمم جرافيك','مطوّر ألعاب','مهندس أنظمة مدمجة',
  'مطوّر البرامج الثابتة','مطوّر الواقع المعزز/الافتراضي', 'مسؤول نظم','مهندس شبكات',
  'مهندس أمن','مطوّر بلوكتشين','مهندس روبوتات','مسؤول قواعد البيانات','مهندس أجهزة',
  'اختصاصي دعم تكنولوجيا المعلومات', 'مهندس حلول','مهندس بنية مؤسسية','كاتب تقني',
  'مدير تقنية المعلومات','مهندس دعم تقني', 'सॉफ्टवेयर इंजीनियर','फ्रंटएंड डेवलपर','बैकएंड डेवलपर',
  'फुल स्टैक डेवलपर', 'वेब डेवलपर','मोबाइल डेवलपर','क्वालिटी एश्योरेंस इंजीनियर','टेस्ट इंजीनियर','डेवऑप्स इंजीनियर',
  'क्लाउड इंजीनियर','साइट रिलायबिलिटी इंजीनियर', 'एआई इंजीनियर','मशीन लर्निंग इंजीनियर', 'डेटा इंजीनियर','डेटा वैज्ञानिक',
  'डेटा विश्लेषक','बिजनेस इंटेलिजेंस विश्लेषक', 'यूएक्स डिजाइनर','यूआई डिजाइनर','प्रोडक्ट डिजाइनर','ग्राफिक डिजाइनर',
  'गेम डेवलपर','एम्बेडेड सिस्टम्स इंजीनियर', 'फर्मवेयर डेवलपर','एआर/वीआर डेवलपर', 'सिस्टम एडमिनिस्ट्रेटर','नेटवर्क इंजीनियर',
  'सिक्योरिटी इंजीनियर','ब्लॉकचेन डेवलपर','रोबोटिक्स इंजीनियर','डेटाबेस एडमिनिस्ट्रेटर','हार्डवेयर इंजीनियर','आईटी सपोर्ट विशेषज्ञ',
  'सोलूशन्स आर्किटेक्ट','एंटरप्राइज आर्किटेक्ट','टेक्निकल राइटर','आईटी मैनेजर','टेक्निकल सपोर्ट इंजीनियर', 'programvaruingenjör',
  'frontendutvecklare','backendutvecklare','fullstackutvecklare', 'webbutvecklare','mobilutvecklare',
  'QA-ingenjör','testingenjör','DevOps-ingenjör','molningenjör','webbplatsens tillförlitlighetsingenjör',
  'AI-ingenjör','maskininlärningsingenjör', 'dataingenjör','dataforskare','dataanalytiker','affärsanalytiker',
  'UX-designer','UI-designer','produktdesigner','grafisk designer','spelutvecklare',
  'embedded systems-ingenjör', 'firmwareutvecklare','AR/VR-utvecklare', 'systemadministratör',
  'nätverksingenjör','säkerhetsingenjör','blockkedjeutvecklare','robotikingenjör','databassadministratör',
  'hårdvaruingenjör','IT-supportspecialist', 'lösningsarkitekt','företagsarkitekt','teknisk skribent',
  'IT-chef','teknisk supportingenjör', 
  'מהנדס תוכנה','מפתח צד קדמי','מפתח צד אחורי','מפתח פול סטאק','מפתח ווב','מפתח מובייל',
  'מהנדס אבטחת איכות','מהנדס בדיקות','מהנדס דבופס','מהנדס ענן','מהנדס אמינות אתר','מהנדס בינה מלאכותית',
  'מהנדס למידת מכונה','מהנדס נתונים','מדען נתונים','אנליסט נתונים','אנליסט מודיעין עסקי',
  'מעצב חוויית משתמש (UX)', 'מעצב ממשק משתמש (UI)', 'מעצב מוצר','מעצב גרפי','מפתח משחקים',
  'מהנדס מערכות משובצות','מפתח קושחה','מפתח AR/VR','מנהל מערכות','מהנדס רשת','מהנדס אבטחה',
  'מפתח בלוקצ\'יין','מהנדס רובוטיקה','מנהל מסדי נתונים','מהנדס חומרה','מומחה תמיכת IT','ארכיטקט פתרונות',
  'ארכיטקט ארגוני','כותב טכני','מנהל IT','מהנדס תמיכה טכנית',

  // Research & Science
  'scientist', 'research scientist', 'clinical research associate',
  'laboratory technician', 'biotechnologist', 'chemist', 'physicist',
  'microbiologist', 'medical researcher', 'environmental scientist',
  'data researcher', 'statistician', 'research assistant','عالِم', 'عالِم أبحاث',  'مساعد أبحاث سريرية',  
  'فني مختبر',  'خبير في التكنولوجيا الحيوية', 'كيميائي', 'فيزيائي', 'عالم أحياء دقيقة', 'باحث طبي',  
  'عالم بيئة',  'باحث بيانات',  'إحصائي', 'مساعد باحث','वैज्ञानिक', 'अनुसंधान वैज्ञानिक',  'क्लिनिकल रिसर्च एसोसिएट',  
  'प्रयोगशाला तकनीशियन',  'बायोटेक्नोलॉजिस्ट', 'रसायनशास्त्री', 'भौतिक विज्ञानी', 'सूक्ष्मजीवविज्ञानी', 'चिकित्सा शोधकर्ता',  
  'पर्यावरण वैज्ञानिक',  'डेटा शोधकर्ता',  'सांख्यिकीविद्', 'शोध सहायक',  'forskare', 'forskningsforskare',  
  'klinisk forskningsassistent',   'laboratorietekniker',  'bioteknolog', 'kemist', 'fysiker', 'mikrobiolog', 
  'medicinsk forskare',  'miljöforskare',  'dataforskare',  'statistiker', 'forskningsassistent', 'מדען','מדען מחקר','עוזר מחקר קליני',
  'טכנאי מעבדה','ביוטכנולוג','כימאי','פיזיקאי','מיקרוביולוג','חוקר רפואי','מדען סביבתי','חוקר נתונים',
  'סטטיסטיקאי','עוזר מחקר',



  // Business & Strategy
  'business analyst', 'strategy consultant', 'strategy lead',
  'business development executive', 'business development manager', 'bdm',
  'corporate strategist', 'operations manager', 'project manager',
  'program manager', 'product manager', 'pmo analyst', 'entrepreneur',
  'founder', 'co-founder', 'innovation manager','محلل أعمال',  'استشاري استراتيجيات',  'قائد استراتيجي',  
  'تنفيذي تطوير الأعمال',  'مدير تطوير الأعمال',  'مدير تطوير الأعمال', 'استراتيجي شركات',  'مدير العمليات',  
  'مدير مشروع',  'مدير برنامج',  'مدير منتج',  'محلل مكتب إدارة المشاريع',  'رائد أعمال', 'مؤسس', 
  'شريك مؤسس', -'مدير الابتكار',  'व्यवसाय विश्लेषक',  'रणनीति सलाहकार',  'रणनीति प्रमुख',  'व्यवसाय विकास कार्यकारी', 
  'व्यवसाय विकास प्रबंधक',  'बीडीएम', 'कॉर्पोरेट रणनीतिकार',  'संचालन प्रबंधक',  'परियोजना प्रबंधक',  'कार्यक्रम प्रबंधक',  
  'उत्पाद प्रबंधक',  'पीएमओ विश्लेषक',  'उद्यमी', 'संस्थापक', 'सह-संस्थापक', 'नवाचार प्रबंधक',  'affärsanalytiker',  
  'strategikonsult',  'strategiansvarig',  'affärsutvecklingsexekutiv','affärsutvecklingschef',   
  'affärsutvecklingschef',  'företagsstrateg',  'operativ chef',  'projektledare',  'programchef',  
  'produktchef',  'pmo-analytiker',  'entreprenör', 'grundare', 'medgrundare', 'innovationschef',  
  'אנליסט עסקי', 'יועץ אסטרטגיה', 'מוביל אסטרטגיה', 'מנהל פיתוח עסקי', 'מנהל בכיר לפיתוח עסקי', 'bdm', 
  'אסטרטג תאגידי', 'מנהל תפעול', 'מנהל פרויקטים', 'מנהל תוכניות', 'מנהל מוצר', 'אנליסט PMO', 
  'יזם', 'מייסד', 'מייסד שותף', 'מנהל חדשנות',

  // Marketing & Sales
  'marketing manager', 'digital marketing specialist', 'seo specialist',
  'sem specialist', 'social media manager', 'content writer', 'copywriter',
  'content strategist', 'creative director', 'brand manager', 'growth hacker',
  'campaign manager', 'influencer manager', 'sales executive', 'sales manager',
  'account manager', 'key account manager', 'customer success manager',
  'crm manager', 'lead generation specialist', 'telemarketer', 'affiliate marketer','مدير تسويق',  
  'أخصائي تسويق رقمي', 'أخصائي تحسين محركات البحث',  'أخصائي تسويق عبر محركات البحث',  
  'مدير وسائل التواصل الاجتماعي', 'كاتب محتوى',  'كاتب إعلانات', 'استراتيجي محتوى',  'المدير الإبداعي',  
  'مدير علامة تجارية',  'هاكر نمو',  'مدير حملة',  'مدير مؤثرين',  'تنفيذي مبيعات',  'مدير مبيعات',  
  'مدير حسابات',  'مدير حساب رئيسي',  'مدير نجاح العملاء', 'مدير إدارة علاقات العملاء',  
  'أخصائي توليد العملاء المحتملين',  'مسوق عبر الهاتف', 'مسوق تابع',  'मार्केटिंग प्रबंधक',  'डिजिटल मार्केटिंग विशेषज्ञ',  
  'एसईओ विशेषज्ञ',  'एसईएम विशेषज्ञ',  'सोशल मीडिया प्रबंधक',  'सामग्री लेखक',  'कॉपीराइटर', 'सामग्री रणनीतिकार', 
  'क्रिएटिव डायरेक्टर',  'ब्रांड प्रबंधक',  'ग्रोथ हैकर',  'अभियान प्रबंधक',  'इन्फ्लुएंसर प्रबंधक',  'सेल्स एग्जीक्यूटिव',  'सेल्स मैनेजर',  
  'खाता प्रबंधक',  'मुख्य खाता प्रबंधक',  'ग्राहक सफलता प्रबंधक', 'सीआरएम प्रबंधक',  'लीड जनरेशन विशेषज्ञ',  'टेलीमार्केटर', 
  'एफिलिएट मार्केटर',  'marknadschef',  'digital marknadsföringsspecialist',  'seo-specialist',  'sem-specialist',  
  'sociala medier-chef', 'innehållsskribent',  'copywriter','innehållsstrateg',  'kreativ chef',  
  'varumärkeschef',  'tillväxthackare',  'kampanjchef',  'influencermanager',  'försäljningsexekutiv',  
  'försäljningschef',  'kontochef',  'nyckelkundsansvarig',  'kundframgångschef',   'crm-chef',  
  'leadgenereringsspecialist',  'telefonförsäljare', 'affiliate-marknadsförare',
  'מנהל שיווק', 'מומחה שיווק דיגיטלי', 'מומחה SEO', 'מומחה SEM', 'מנהל מדיה חברתית', 'כותב תוכן', 
  'קופירייטר', 'אסטרטג תוכן', 'מנהל קריאייטיב', 'מנהל מותג', 'האקר צמיחה', 'מנהל קמפיינים', 
  'מנהל משפיענים', 'מנהל מכירות', 'נציג מכירות', 'מנהל חשבונות', 'מנהל חשבונות מפתח', 'מנהל הצלחת לקוח', 
  'מנהל CRM', 'מומחה להפקת לידים', 'טלמרקטינג', 'משווק שותפים',

  // Human Resources & Administration
  'hr manager', 'hr generalist', 'hr specialist', 'recruiter', 'technical recruiter',
  'talent acquisition manager', 'people operations manager',
  'compensation and benefits analyst', 'l&d specialist',
  'diversity and inclusion officer', 'organizational development specialist',
  'administrative assistant', 'office manager', 'executive assistant','مدير الموارد البشرية',  'أخصائي موارد بشرية عام',  'أخصائي موارد بشرية',  'مسؤول توظيف','مسؤول توظيف تقني',  'مدير اكتساب المواهب',   'مدير عمليات الأفراد',   'محلل التعويضات والمزايا', 'أخصائي التعلم والتطوير','مسؤول التنوع والشمول', 'أخصائي تطوير تنظيمي',   'مساعد إداري',  'مدير مكتب',  'مساعد تنفيذي',  
  'एचआर प्रबंधक',  'एचआर जनरलिस्ट',  'एचआर विशेषज्ञ',  'भर्ती करने वाला','तकनीकी भर्ती करने वाला',  
  'प्रतिभा अधिग्रहण प्रबंधक',   'लोग संचालन प्रबंधक',   'मुआवजा और लाभ विश्लेषक', 'एल एंड डी विशेषज्ञ',
  'विविधता और समावेशन अधिकारी', 'संगठनात्मक विकास विशेषज्ञ', 'प्रशासनिक सहायक',  'कार्यालय प्रबंधक',  
  'कार्यकारी सहायक','hr-chef',  'hr-generalist',  'hr-specialist',  'rekryterare','teknisk rekryterare',  
  'chef för talanganskaffning',   'people operations manager',   'analytiker för ersättning och förmåner', 
  'specialist inom lärande och utveckling',  'ansvarig för mångfald och inkludering', 
  'specialist på organisationsutveckling',   'administrationassistent',  'kontorschef',  'exekutiv assistent',  
  'מנהל משאבי אנוש', 'כללמש"א', 'מומחה משאבי אנוש', 'מגייס', 'מגייס טכנולוגי', 'מנהל גיוס טאלנטים', 
  'מנהל תפעול עובדים', 'אנליסט תגמולים והטבות', 'מומחה הדרכה ופיתוח', 'אחראי גיוון והכללה', 
  'מומחה לפיתוח ארגוני', 'עוזר מנהלי', 'מנהל משרד', 'עוזר בכיר',

  // Finance & Legal
  'accountant', 'finance manager', 'controller', 'financial analyst',
  'investment analyst', 'risk manager', 'tax specialist', 'bookkeeper',
  'internal auditor', 'compliance officer', 'legal counsel', 'paralegal',
  'corporate lawyer', 'contracts manager','محاسب', 'مدير المالية',   'مراقب مالي', 'محلل مالي', 
  'محلل استثمار',   'مدير المخاطر',   'أخصائي ضرائب',   'مسؤول دفاتر الحسابات', 'مدقق داخلي',   
  'مسؤول الالتزام',   'مستشار قانوني',   'مساعد قانوني', 'محامي شركات',   'مدير العقود',   'लेखाकार', 
  'वित्त प्रबंधक',   'नियंत्रक', 'वित्तीय विश्लेषक',   'निवेश विश्लेषक',   'जोखिम प्रबंधक',   'कर विशेषज्ञ',   'बुककीपर', 
  'आंतरिक लेखा परीक्षक',   'अनुपालन अधिकारी',   'कानूनी सलाहकार',   'पैरालीगल', 'कॉर्पोरेट वकील',   'अनुबंध प्रबंधक',   
  'redovisningsekonom', 'finanschef',   'controller', 'finansiell analytiker',   'investeringanalytiker',   
  'riskchef',   'skattespecialist',   'bokförare', 'intern revisor',   'compliance officer',   
  'juridisk rådgivare',   'paralegal', 'bolagsjurist',   'kontraktschef',   
  'רואה חשבון', 'מנהל כספים', 'בקר פיננסי', 'אנליסט פיננסי', 'אנליסט השקעות', 'מנהל סיכונים', 
  'מומחה מיסוי', 'מנה"ח', 'מבקר פנימי', 'אחראי ציות', 'יועץ משפטי', 'עוזר משפטי', 'עורך דין חברות', 
  'מנהל חוזים',

  // Customer Service & Support
  'customer support specialist', 'customer success representative',
  'support engineer', 'help desk technician', 'call center representative',
  'technical support agent', 'client relationship manager', 'field service technician','أخصائي دعم العملاء',  
  'ممثل نجاح العملاء',  'مهندس دعم','فني مكتب المساعدة',  'ممثل مركز الاتصال',  'وكيل الدعم الفني', 
  'مدير علاقات العملاء',  'فني خدمة ميدانية',   'ग्राहक सहायता विशेषज्ञ',  'ग्राहक सफलता प्रतिनिधि',  'सपोर्ट इंजीनियर',
  'हेल्प डेस्क तकनीशियन',  'कॉल सेंटर प्रतिनिधि',  'तकनीकी सहायता एजेंट',  'क्लाइंट रिलेशनशिप मैनेजर',  'फील्ड सर्विस तकनीशियन',
  'kundsupportspecialist',  'kundframgångsrepresentant',  'supportingenjör','hjälpdesktekniker',  
  'callcenterrepresentant',  'teknisk supportagent',  'kundrelationschef',  'fältsservicetekniker',  
  'מומחה תמיכת לקוחות', 'נציג הצלחת לקוחות', 'מהנדס תמיכה', 'טכנאי דסק תמיכה', 'נציג מוקד טלפוני', 
  'סוכן תמיכה טכנית', 'מנהל קשרי לקוחות', 'טכנאי שירות שטח',

  // Industrial & Manufacturing
  'mechanical engineer', 'electrical engineer', 'civil engineer',
  'industrial engineer', 'manufacturing engineer', 'plant manager',
  'production supervisor', 'quality control inspector', 'operations supervisor',
  'maintenance technician', 'assembly line worker', 'cnc operator','مهندس ميكانيكي','مهندس كهربائي',
  'مهندس مدني','مهندس صناعي','مهندس تصنيع','مدير المصنع','مشرف الإنتاج','مفتش مراقبة الجودة',
  'مشرف العمليات','فني صيانة','عامل خط التجميع','مشغل ماكينة CNC','मैकेनिकल इंजीनियर','इलेक्ट्रिकल इंजीनियर',
  'सिविल इंजीनियर','औद्योगिक इंजीनियर','निर्माण इंजीनियर','प्लांट मैनेजर','उत्पादन पर्यवेक्षक','गुणवत्ता नियंत्रण निरीक्षक',
  'ऑपरेशन पर्यवेक्षक','रखरखाव तकनीशियन','असेंबली लाइन वर्कर','CNC ऑपरेटर','mekanisk ingenjör','elektrisk ingenjör',
  'civilingenjör','industriengineer','tillverkningsingenjör','plantchef','produktionsövervakare',
  'kvalitetskontrollinspektör','operationsövervakare','underhållstekniker','sammansättningsarbetare',
  'CNC-operatör','מהנדס מכונות', 'מהנדס חשמל', 'מהנדס אזרחי', 'מהנדס תעשייה', 'מהנדס ייצור', 'מנהל מפעל', 
  'מפקח ייצור', 'בודק בקרת איכות', 'מפקח תפעול', 'טכנאי תחזוקה', 'עובד פס ייצור', 'מפעיל CNC',

  // Supply Chain & Logistics
  'supply chain manager', 'logistics coordinator', 'procurement specialist',
  'inventory manager', 'warehouse manager', 'purchasing agent',
  'operations planner', 'distribution manager', 'transportation manager','freight coordinator',
  'مدير سلسلة التوريد','منسق اللوجستيات','أخصائي المشتريات','مدير المخزون','مدير المستودع',
  'وكيل المشتريات','مخطط العمليات','مدير التوزيع','مدير النقل','منسق الشحن','सप्लाई चेन मैनेजर',
  'लॉजिस्टिक्स समन्वयक','खरीद विशेषज्ञ','इन्वेंटरी मैनेजर','वेयरहाउस मैनेजर','खरीद एजेंट','ऑपरेशन्स योजनाकार','वितरण प्रबंधक',
  'परिवहन प्रबंधक','फ्रेट समन्वयक','supply chain manager','logistikkoordinator','inköpsspecialist','inventariechef',
  'lagerchef','inköpsagent','operationsplanerare','distributionschef','transportchef','fraktkoordinator',
  'מנהל שרשרת אספקה', 'רכז לוגיסטיקה', 'מומחה רכש', 'מנהל מלאי', 'מנהל מחסן', 'סוכן רכש', 'מתכנן תפעול', 
  'מנהל הפצה', 'מנהל תחבורה', 'רכז שילוח',

  // Healthcare & Medical
  'medical doctor', 'nurse', 'pharmacist', 'physical therapist',
  'nutritionist', 'dietician', 'radiologist', 'health services manager',
  'medical assistant', 'caregiver', 'medical receptionist', 'telehealth specialist',
  'surgeon', 'dentist','طبيب','ممرضة','صيدلي','أخصائي علاج طبيعي','أخصائي تغذية','اختصاصي تغذية',
  'أخصائي أشعة','مدير خدمات صحية', 'مساعد طبيب','مقدم رعاية','موظف استقبال طبي',
  'أخصائي الرعاية الصحية عن بُعد','جراح','طبيب أسنان','चिकित्सक','नर्स','फार्मासिस्ट','फिजिकल थेरेपिस्ट','पोषण विशेषज्ञ',
  'डायटीशियन','रेडियोलॉजिस्ट','स्वास्थ्य सेवा प्रबंधक', 'मेडिकल असिस्टेंट','देखभालकर्ता','मेडिकल रिसेप्शनिस्ट','टेलीहेल्थ विशेषज्ञ',
  'सर्जन','दंत चिकित्सक','läkare','sjuksköterska','apotekare','fysioterapeut','nutritionist','dietist','radiolog',
  'chef för hälsovårdstjänster', 'medisinsk assistent','vårdare','mottagningssekreterare','telehälsospecialist',
  'kirurg','tandläkare','רופא', 'אחות', 'רוקח', 'פיזיותרפיסט', 'תזונאי', 'דיאטן', 'רדיולוג', 'מנהל שירותי בריאות', 
  'עוזר רפואי', 'מטפל', 'פקידת קבלה רפואית', 'מומחה ברפואה מרחוק', 'מנתח', 'רופא שיניים',

  // Education & Training
  'teacher', 'professor', 'lecturer', 'teaching assistant', 'academic advisor',
  'curriculum developer', 'instructional designer', 'training coordinator',
  'educational consultant', 'e-learning developer','معلم','أستاذ','محاضر','مساعد تدريس','مستشار أكاديمي',
  'مطور المناهج','مصمم تعليمي','منسق التدريب','مستشار تعليمي','مطور التعلم الإلكتروني', 
  'शिक्षक','प्रोफेसर','लेक्चरर','शिक्षण सहायक','शैक्षणिक सलाहकार','पाठ्यक्रम डेवलपर','निर्देशन डिजाइनर','प्रशिक्षण समन्वयक',
  'शैक्षिक सलाहकार','ई-लर्निंग डेवलपर', 'lärere','professor','föreläsare','undervisningsassistent',
  'akademisk rådgivare','kursutvecklare','instruktionsdesigner','utbildningskoordinator','utbildningskonsult',
  'e-lärandeutvecklare', 'מורה', 'פרופסור', 'מרצה', 'עוזר הוראה', 'יועץ אקדמי', 'מפתח תוכנית לימודים', 
  'מעצב הדרכה', 'רכז הדרכה', 'יועץ חינוכי', 'מפתח למידה אלקטרונית',


  // Creative & Media
  'creative director', 'art director', 'photographer', 'videographer',
  'video editor', 'motion graphics designer', 'animator', 'illustrator',
  'editor', 'journalist', 'content creator', 'fashion designer',
  'interior designer', 'مدير إبداعي', 'مدير فني', 'مصور', 'مصور فيديو', 'محرر فيديو', 
  'مصمم رسوم متحركة',   'محرك رسوم متحركة', 'رسام توضيحي', 'محرر', 'صحفي', 'صانع محتوى', 
  'مصمم أزياء', 'مصمم داخلي', 'क्रिएटिव डायरेक्टर', 'आर्ट डायरेक्टर', 'फोटोग्राफर', 'विडियोग्राफर', 'वीडियो एडिटर',
  'मोशन ग्राफिक्स डिजाइनर',   'एनिमेटर', 'इलस्ट्रेटर', 'संपादक', 'पत्रकार', 'सामग्री निर्माता', 'फैशन डिजाइनर', 
  'इंटीरियर डिजाइनर', 'kreativ chef', 'konstnärlig ledare', 'fotograf', 'videograf', 'video redaktör',
  'rörlig grafikdesigner',   'animatör', 'illustratör', 'redaktör', 'journalist', 'innehållsskapare',
  'modedesigner', 'inredningsdesigner','מנהל קריאייטיב', 'מנהל אמנות', 'צלם', 'צלם וידאו', 'עורך וידאו', 
  'מעצב גרפיקה מונפשת', 'אנימטור', 'מאייר', 'עורך', 'עיתונאי', 'יוצר תוכן', 'מעצב אופנה', 'מעצב פנים',

  // Other / Entry-Level / General Roles
  'intern', 'trainee', 'assistant', 'office clerk', 'data entry clerk',
  'technician', 'field technician', 'janitor', 'cleaner', 'security guard',
  'delivery driver', 'receptionist', 'concierge','متدرب','متدرب عملي',
  'مساعد', 'كاتب مكتب', 'كاتب إدخال بيانات','فني','فني ميداني','عامل نظافة',
  'عامل تنظيف','حارس أمن', 'سائق توصيل', 'موظف استقبال', 'كونسيرج', 'इंटर्न', 'प्रशिक्षु',
  'सहायक', 'दफ्तर क्लर्क', 'डेटा एंट्री क्लर्क', 'तकनीशियन', 'फील्ड तकनीशियन', 'जानेटर', 'सफाई कर्मचारी', 
  'सुरक्षा गार्ड', 'डिलीवरी ड्राइवर','रिसेप्शनिस्ट', 'कांसीयज', 'praktikant','lärling', 'assistent', 'kontorskl clerk',
  'dataregistreringskl clerk', 'tekniker','fälttekniker',  'vaktmästare','städare','säkerhetsvakt', 
  'budbilschaufför', 'receptionist', 'concierge','המתמחה', 'חניך', 'עוזר', 'פקיד משרדי', 'פקיד הזנת נתונים',
  'טכנאי', 'טכנאי שטח', 'שומר', 'מנקה', 'שומר ביטחון', 'שליח', 'פונקציונר קבלה', 'קונסיירז׳'   
];

const industries = [
  'it',
  'tech',
  'finance',
  'education',
  'healthcare',
  'biotechnology',
  'pharmaceuticals',
  'aerospace',
  'automotive',
  'agriculture',
  'construction',
  'real estate',
  'manufacturing',
  'media',
  'entertainment',
  'telecommunications',
  'retail',
  'ecommerce',
  'transportation',
  'logistics',
  'tourism',
  'hospitality',
  'energy',
  'utilities',
  'mining',
  'legal',
  'consulting',
  'marketing',
  'advertising',
  'insurance',
  'non-profit',
  'public sector',
  'government',
  'military',
  'environmental',
  'fashion',
  'food and beverage',
  'gaming',
  'sports',
  'blockchain',
  'cybersecurity',
  'design',
  'arts and culture',
  'electronics',
  'printing and publishing',
  'fitness and wellness',
  'recruitment',
  'human resources',
  'event management',
  'marine',
  'audiovisual',
  'AI and machine learning'
];

module.exports = {
  formatDate,
  positions,
  industries
}; 